<a href="https://colab.research.google.com/github/Ukejee/HamoyeIntern/blob/master/Data_ScienceQuiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

#pd.set_option('display.width', 400)
#pd.set_option('display.max_columns', 15)
fuel_data = pd.read_csv("https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv")

#Question One
A = [1,2,3,4,5,6]
B = [13, 21, 34]

a = pd.Series(A)
b = pd.Series(B)
A_B = a.append(b)
print(A_B)

#Question Two
print(np.identity((3)))

#Question Three
print(fuel_data.groupby("fuel_type_code_pudl")["fuel_cost_per_unit_burned"].describe())

#Question Four
print(fuel_data.describe().to_string())

#Question Five
print(fuel_data["fuel_qty_burned"].skew())
print(fuel_data["fuel_qty_burned"].kurtosis())

#Question Six
print(fuel_data.isnull().sum())
print(fuel_data["fuel_unit"].count())
print(fuel_data.isnull().sum()/fuel_data["fuel_unit"].count() * 100)

#Question Eight
print(fuel_data.corr(method="pearson").to_string)

#Question Nine
print(fuel_data.groupby("report_year")["fuel_cost_per_unit_burned"].describe())

#Question Ten
print(fuel_data.groupby("report_year")["fuel_cost_per_unit_delivered"].describe())

0     1
1     2
2     3
3     4
4     5
5     6
0    13
1    21
2    34
dtype: int64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
                       count         mean  ...       75%         max
fuel_type_code_pudl                        ...
coal                  8547.0    67.421830  ...  44.66800   44033.320
gas                  11486.0    13.659397  ...   6.96000   10490.000
nuclear                818.0  4955.157002  ...  50.85525   69785.215
oil                   8064.0   168.877086  ...  98.68925  139358.000
other                  167.0    18.253856  ...  20.05500     134.547
waste                  441.0    19.518122  ...  32.65000     132.291

[6 rows x 8 columns]
       utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu
count      29523.000000  29523.000000     2.952300e+04         29523.000000               29523.000000                  2.952300e+04         29523.000000
mean         118.601836   2005.806050     2.622119e+06             8.492111                 208.649031                  9.175704e+02            19.304354
std           74.178353      7.025483     9.118004e+06            10.600220                2854.490090                  6.877593e+04          2091.540939
min            1.000000   1994.000000     1.000000e+00             0.000001                -276.080000                 -8.749370e+02           -41.501000
25%           55.000000   2000.000000     1.381700e+04             1.024000                   5.207000                  3.778500e+00             1.940000
50%          122.000000   2006.000000     2.533220e+05             5.762694                  26.000000                  1.737100e+01             4.127000
75%          176.000000   2012.000000     1.424034e+06            17.006000                  47.113000                  4.213700e+01             7.745000
max          514.000000   2018.000000     5.558942e+08           341.260000              139358.000000                  7.964521e+06        359278.000000
15.851495469109503
651.3694501337732
record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64
29343
record_id                       0.000000
utility_id_ferc1                0.000000
report_year                     0.000000
plant_name_ferc1                0.000000
fuel_type_code_pudl             0.000000
fuel_unit                       0.613434
fuel_qty_burned                 0.000000
fuel_mmbtu_per_unit             0.000000
fuel_cost_per_unit_burned       0.000000
fuel_cost_per_unit_delivered    0.000000
fuel_cost_per_mmbtu             0.000000
dtype: float64
<bound method DataFrame.to_string of                               utility_id_ferc1  ...  fuel_cost_per_mmbtu
utility_id_ferc1                      1.000000  ...             0.006122
report_year                           0.093323  ...             0.010261
fuel_qty_burned                      -0.057447  ...            -0.001896
fuel_mmbtu_per_unit                  -0.066946  ...            -0.005884
fuel_cost_per_unit_burned            -0.037863  ...            -0.000437
fuel_cost_per_unit_delivered         -0.016414  ...            -0.000109
fuel_cost_per_mmbtu                   0.006122  ...             1.000000

[7 rows x 7 columns]>
              count        mean          std  ...      50%        75%         max
report_year                                   ...
1994         1235.0  213.191996  2639.254133  ...  20.2900   35.76650   44009.190
1995         1201.0  354.422555  3793.484721  ...  18.8000   34.42000   62609.000
1996         1088.0   79.434995  1414.289963  ...  18.9640   31.47050   33150.000
1997         1094.0  149.482132  2210.821082  ...  17.9945   31.09000   48164.000
1998         1107.0  126.683519  2099.842843  ...  11.8300   29.70950   54376.000
1999         1050.0  120.053605  1497.959005  ...  12.3340   29.39775   31640.600
2000         1373.0  237.797111  2761.109267  ...  25.1500   34.43000   51698.000
2001         1356.0  133.013010  1697.434281  ...  27.0745   37.09475   34652.000
2002         1205.0  101.179365  1577.523780  ...  24.0600   33.64500   35486.000
2003         1211.0  123.183919  1673.762142  ...  26.8200   38.04300   34518.000
2004         1192.0  154.897398  1897.420633  ...  27.9165   43.08850   31825.840
2005         1269.0  107.111221  1521.842893  ...  29.9400   56.30100   35948.000
2006         1243.0  151.361249  2063.586510  ...  30.5700   66.81000   43851.000
2007         1264.0  202.622082  2534.590480  ...  32.0400   72.04200   45486.000
2008         1228.0  255.954415  2718.547425  ...  33.5205   81.93800   45578.820
2009         1222.0  215.699318  2626.629546  ...  34.8540   78.81250   49650.832
2010         1261.0  262.951203  3234.104603  ...  35.2590   86.07300   64313.100
2011         1240.0  301.754519  4039.739595  ...  35.5685   94.08750   83538.000
2012         1243.0  258.804138  3429.645744  ...  38.0310  100.79800   65137.588
2013         1199.0  255.991023  3496.961958  ...  38.3180  101.62250   61717.765
2014         1171.0  442.359068  5754.143709  ...  38.6790  108.24800  139358.000
2015         1093.0  237.933197  3151.231506  ...  32.1870   84.42000   53889.540
2016         1034.0  247.083959  3317.538986  ...  27.3700   64.20800   55098.539
2017          993.0  246.281796  3134.321819  ...  28.4830   70.75000   51417.892
2018          951.0  232.992036  2810.868978  ...  24.7380   78.67300   44738.780

[25 rows x 8 columns]
              count          mean  ...        75%          max
report_year                        ...
1994         1235.0     63.636060  ...   30.91000    45115.000
1995         1201.0     32.735269  ...   29.79000     2396.770
1996         1088.0   9196.705948  ...   30.57250  7793482.000
1997         1094.0  11140.197239  ...   29.10400  7964521.000
1998         1107.0    287.154420  ...   24.78000   270604.000
1999         1050.0     25.551627  ...   26.12300     2891.100
2000         1373.0    985.362877  ...   36.28800  1168000.000
2001         1356.0     60.050396  ...   35.78250    34381.000
2002         1205.0     47.594361  ...   31.96000    31416.000
2003         1211.0     55.663493  ...   37.44100    34518.000
2004         1192.0    139.524275  ...   45.84025   132884.000
2005         1269.0     41.438184  ...   62.13000     8651.000
2006         1243.0     38.657484  ...   68.49700     1431.000
2007         1264.0     43.325023  ...   72.66500     4850.872
2008         1228.0     58.588197  ...   80.97925    10490.000
2009         1222.0    652.694163  ...   71.45950   730166.000
2010         1261.0     91.862105  ...   86.36000    44033.320
2011         1240.0     59.774667  ...   92.69675     9545.000
2012         1243.0     60.994502  ...   99.53500    10129.000
2013         1199.0    172.307591  ...   90.49000   135315.000
2014         1171.0    192.737183  ...  103.24750   136410.000
2015         1093.0    326.535511  ...   67.46000   140706.000
2016         1034.0    103.901761  ...   54.04875    69440.000
2017          993.0     46.196861  ...   62.93000     3584.335
2018          951.0    499.269966  ...   70.43900   245652.000

[25 rows x 8 columns]